services:
  - type: web
    name: backendpms
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
