services:
  - type: web
    name: backendpms
    env: node
    plan: free
    buildCommand: |
      pnpm install --no-frozen-lockfile
      pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLERK_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
