services:
  - type: web
    name: backendpms
    env: node
    buildCommand: chmod +x scripts/build.sh && ./scripts/build.sh
    startCommand: pnpm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
