services:
  - type: web
    name: backendpms
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
